name: Multi Job Workflow

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Job 1
        run: echo "Hello from Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1 - Job 2
        run: echo "Job 2 will run only after Job 1 finishes"
